name: Deploy to production
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Deploy to production
        env:
          DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DB_USER: ${{ secrets.DATABASE_USER }}
          JWT: ${{ secrets.JWT_SECRET }}
        run: |

          cd /home/smaug/sites/alexandrie/
          git reset --hard HEAD
          git pull origin main
          cd /home/smaug/sites/alexandrie/backend
          npm install -D --no-save
          npm run build
          cd /home/smaug/sites/alexandrie/frontend
          npm install -D --no-save
          npm run build 
          cd /home/smaug/sites/alexandrie/dashboard
          npm install -D --no-save
          npm run build 
          cd /home/smaug/sites/alexandrie/
          NODE_ENV=production DOCS_SERVER_PORT=3110 CLIENT="https://alexandrie-hub.fr" FRONT_DOMAIN="smaug-6739.dev" DATABASE_PASSWORD=$DB_PASSWORD DATABASE_USER=$DB_USER JWT_SECRET=$JWT pm2 reload ecosystem.config.js --update-env
