name: Deploy to production
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Deploy to production
        run: |
          cd /home/smaug/sites/docs-website/
          git pull origin main
          cd /home/smaug/sites/docs-website/backend
          npm install -D
          npm run build
          cd /home/smaug/sites/docs-website/frontend
          npm install -D
          npm run build 
          cd /home/smaug/sites/docs-website/
