name: Deploy to production
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Deploy to production
        env:
          DB_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DB_USER: ${{ secrets.DATABASE_USER }}
          JWT: ${{ secrets.JWT_SECRET }}
        run: |

          cd /home/smaug/sites/docs-website/
          git pull origin main
          cd /home/smaug/sites/docs-website/backend
          npm install -D
          npm run build
          cd /home/smaug/sites/docs-website/frontend
          npm install -D
          npm run build 
          cd /home/smaug/sites/docs-website/
          VITE_BASE_API="https://api.docs.smaug-6739.dev" FRONT_DOMAIN="https://docs.smaug-6739.dev" DATABASE_PASSWORD=$DB_PASSWORD DATABASE_USER=$DB_USER JWT_SECRET=$JWT NODE_ENV=production pm2 reload ecosystem.config.js --update-env
