name: Deploy to production
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: cd backend && npm ci

      - name: Build
        run: cd backend && npm run build

      - uses: actions/checkout@v3
      - run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b deploy
          git add .
          git commit -am "Deploy"
          git push origin deploy
